version: '3'
services:
  jinny-remind:
    build: .
    container_name: jinny-remind
    networks:
      - outside
    # environment:
    #   TZ: "Asia/Hong_Kong"
    environment:
      REMIND_TOKEN:
    command: >
      bash -c "ln -snf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime && 
      echo Asia/Hong_Kong > /etc/timezone &&
      python ./jinny_reminds.py"
networks:
  outside:
    external:
      name: mongonet
