version: '3'
services:
  jinny-remind:
    build: .
    container_name: jinny-remind
    networks:
      - outside
    command: python ./jinny_reminds.py
networks:
  outside:
    external:
      name: mongonet
