version: '3'
services:
  jinny-remind:
    build: .
    container_name: jinny-remind
    networks:
      - outside
    command: tail -f /dev/null 
networks:
  outside:
    external:
      name: mongonet