version: '3'
services:
  jinny-remind:
    build: .
    container_name: jinny-remind
    networks:
      - outside
    environment:
      TZ: "Asia/Hong_Kong"
    command: >
      bash -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      echo $TZ > /etc/timezone &&
      python ./jinny_reminds.py"
networks:
  outside:
    external:
      name: mongonet
